name: Build

on:
  workflow_dispatch:
  push:
    paths:
      - Dockerfile
      - .github/workflows/build.yml
permissions: write-all

jobs:
  build-pytorch:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@master
      - name: Login to GitHub Container Registry
        uses: docker/login-action@master
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to DockerHub
        uses: docker/login-action@master
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PAT }}
      - name: Build and push
        uses: docker/build-push-action@master
        env:
          BASE: "jupyter/minimal-notebook"
          VERSION: "python-3.10"
        with:
          context: .
          file: pytorch.Dockerfile
          platforms: linux/amd64
          push: true
          build-args: |
            BASE=${{ env.BASE }}
            VERSION=${{ env.VERSION }}
          tags: |
            ${{ github.repository_owner }}/jupyter-notebook:latest
            ${{ github.repository_owner }}/jupyter-notebook:pytorch-latest
            ${{ github.repository_owner }}/jupyter-notebook:pytorch-${{ env.VERSION }}
            ghcr.io/${{ github.repository_owner }}/jupyter-notebook:latest
            ghcr.io/${{ github.repository_owner }}/jupyter-notebook:pytorch-latest
            ghcr.io/${{ github.repository_owner }}/jupyter-notebook:pytorch-${{ env.VERSION }}
  final:
    name: Clean-up and add README
    needs: [build-pytorch]
    runs-on: ubuntu-latest
    steps:
      - name: Delete untagged
        uses: dylanratcliffe/delete-untagged-containers@main
        with:
          package_name: jupyter-notebook
          token: ${{ secrets.PAT }}
          user: ${{ github.repository_owner }}
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@main
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PAT }}
          repository: ${{ github.repository_owner }}/jupyter-notebook
          short-description: "Ready-to-run Docker images containing Jupyter applications."
          readme-filepath: README.md
